### PR TITLE
Added index to to_addr

### PR DESCRIPTION
**Pull request by jpaidoussi**
Adding this index to our live databases is going to be very slow due to the size of the table affected, so it should only be done after hours.

### CODE REVIEW

**Comment by smn** [comment]
Is there a way we can do this concurrently?

**Comment by jpaidoussi** [comment]
@smn I think the only way right now would be to change the migration to run custom SQL.

**Comment by smn** [comment]
hm any idea on how long this migration will take without concurrently? It'll mean downtime for the system.

**Comment by smn** [comment]
let's get this one over with @jpaidoussi & @miltontony

**Review by miltontony — APPROVED** [review]
👍

**Pull request merged**
